# Generated by Django 3.2.12 on 2022-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multiplo',
            field=models.IntegerField(default=0, verbose_name='multiplo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiveditems',
            name='multiplo',
            field=models.IntegerField(default=1, verbose_name='multiplo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiveditems',
            name='multiplo_check',
            field=models.BooleanField(default=False),
        ),
    ]
