# Generated by Django 3.2.12 on 2022-02-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Id')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.BooleanField(default=False, verbose_name='Importado')),
                ('outofline', models.BooleanField(default=False, verbose_name='Fora de Linha')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('product', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='IPI')),
                ('stock', models.IntegerField(default='0', null=True, verbose_name='Estoque atual')),
                ('stock_min', models.PositiveIntegerField(default=0, verbose_name='Estoque Minimo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swayapp.brand', verbose_name='marca')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swayapp.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sale', to='swayapp.customer', verbose_name='cliente')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_sale', to='swayapp.seller', verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preço de venda')),
                ('ipi_sale', models.DecimalField(decimal_places=2, default=0.1, max_digits=3, verbose_name='IPI')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_det', to='swayapp.product', verbose_name='produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_det', to='swayapp.sale')),
            ],
        ),
    ]
