# Generated by Django 3.2.12 on 2022-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0002_brand_category_product_sale_saledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='received',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='received_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='received_price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=7, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
