# Generated by Django 3.2.12 on 2022-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0002_auto_20220702_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveditems',
            name='multiplo',
            field=models.IntegerField(verbose_name='Caixa'),
        ),
    ]
