# Generated by Django 3.2.12 on 2022-07-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0003_alter_receiveditems_multiplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_kind', models.TextField(verbose_name='Tipo de Avaria')),
            ],
            options={
                'verbose_name': 'Avaria',
                'verbose_name_plural': 'Avarias',
            },
        ),
        migrations.AlterField(
            model_name='receiveditems',
            name='multiplo_check',
            field=models.BooleanField(default=False, verbose_name='Caixa/Multiplo'),
        ),
    ]
