# Generated by Django 3.2.12 on 2022-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0003_auto_20220211_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='received_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço Recebimento'),
        ),
    ]
