# Generated by Django 3.2.12 on 2022-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0004_alter_product_received_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='received_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Preço Recebimento'),
        ),
    ]
