# Generated by Django 3.2.12 on 2022-02-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0006_receiveditems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiveditems',
            options={'ordering': ['product'], 'verbose_name': 'Received', 'verbose_name_plural': 'Receiveds'},
        ),
    ]
