# Generated by Django 3.2.12 on 2022-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0007_alter_receiveditems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveditems',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
