# Generated by Django 3.2.12 on 2022-02-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swayapp', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='IPI'),
        ),
    ]
